# Generated by Django 4.2 on 2023-04-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_portfolio_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='investment',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
